### ISSUE TITLE
Possibility to rename pk to id or something else

### ISSUE THREAD

**Issue by ryou90** [strawberry-graphql/strawberry-django#121]
Currently, when a filter is created for a single object, "pk" is used as the ID name. There is no possibility to specify an alternative name.

## Feature Request Type

- Change (enhancement/optimization) of an existing feature.

## Description
Ability to set custom name for "pk".

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/121">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/121/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/121/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
an example of this:

```python
@strawberry.type
class Query:
  foo = strawberry.django.field()
```

I wonder how we can customise the name of the argument, we could that on the type, or on the field. I'm not sure what the best option is

**Comment by bellini666** [comment]
@patrick91 maybe something similar to what I did on CUD mutations? Add a field to define the argument name to be used in this case, which users can customer on a per-field settings, and also a django setting to define the global default one, defaulting to `pk`.
