### ISSUE TITLE
Filter should have default settings for different types to make the graphiql cleaner.

### ISSUE THREAD

**Issue by ccsv** [strawberry-graphql/strawberry-django#142]
Different data types should have pre-set filters parameters by default instead of having all the different types of filter applied for each type.

Currently if you apply filters in the graphiql it has all the filters by default  as seen here: https://i.stack.imgur.com/D3zeO.jpg

I would propose to have something like these rules for default:

id: exact, inlist
string: contains, endswith, icontains, iexact/exact, iregex, isnull, startswith, inlist
int/float: exact/iexact, gt, gte, lt, lte, range, isnull, inlist

Some logic like anything with required! should not have isnull

Also an option on the filter when writing the class to modify the filters if you want something not preset as default.

This will make the Graphiql interface more clean and less confusing .

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/142">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/142/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/142/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
https://github.com/strawberry-graphql/strawberry-django/pull/478
