### ISSUE TITLE
List of union type field always yields the first type

### ISSUE THREAD

**Issue by toddy-corpjurist** [strawberry-graphql/strawberry-django#186]
I declared a field which returns a list of union of Django types (those generated by `@strawberry.django.type`). Unfortunately, the returned list only contains elements of the first type stated in a union.

## Describe the Bug

There is a generic relation field which relates to multiple data models in my project. So, I would like to create a field which retrieves its related data model instances, ignoring their type.

For example, I have these data models:
1. Questionnaire
2. AbstractQuestion
3. AbstractChoiceQuestion (inherits AbstractQuestion)
4. SingleSelectionChoiceQuestion (inherits AbstractChoiceQuestion)
5. MultipleSelectionChoiceQuestion (inherits AbstractChoiceQuestion)
6. TextQuestion (inherits AbstractQuestion)

A questionnaire question would relate to either a single selection choice question, a multiple selection choice question or a text question. There can be multiple questions in one questionnaire. Therefore, I wrote a method field (using `@strawberry.field`) which returns `List[ Union[ SingleSelectionChoiceQuestion, MultipleSelectionChoiceQuestion, TextQuestion ] ]` but all I got were a list of `SingleSelectionChoiceQuestion`. Should I explicitly construct a corresponding type instance for each data model instance before returning?

The fun part:
1. If I were to rearrange the union types order, it always picks the first one.
2. I tried this similar trick on `@strawberry.type`, not `@strawberry.django.type`, and it worked correctly. See the `test` method in a code below.

## System Information

 - Operating system: macOS Monterey
 - Strawberry version (if applicable): 0.128.0

## Additional Context

```
@strawberry.type
class Test1:
    value: int

@strawberry.type
class Test2:
    value: int

@strawberry.django.type(models.Questionnaire)
class Questionnaire:
    id: strawberry.auto

    @strawberry.field
    def questions(self) -> List[
        Union[
            "SingleSelectionChoiceQuestion",
            "MultipleSelectionChoiceQuestion",
            "TextQuestion"
        ]
    ]:
        return self.get_questions() # Of course, I checked this method. It returns a list of different question type instances correctly.

    @strawberry.field
    def test(self) -> List [ Union [ Test1, Test2 ] ]:
        return [Test2(value=1), Test1(value=2)]
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/186">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/186/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/186/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @toddy-corpjurist ,

Both strawberry and strawberry-django have gone through a lot of improvements and bug fixes. Does the newest version still have this issue?

**Comment by bellini666** [comment]
Going to close this as fixed, but please comment here in case it is not

**Comment by pcraciunoiu** [comment]
I was thinking of filing a new, similar issue, but I came across this.

@bellini666 when the return type is a union, I'm having trouble figuring out how to construct a strawberry type for each object in the queryset if the graphql type depends on e.g. a property on that object. I've declared strawberry types for each. What's the best way to return the correct strawberry type from a list of model instances/queryset? In graphene I was used to a `resolve_type` function on the union, but that's different for strawberry.

Edit: This must be the answer I was looking for!
https://strawberry.rocks/docs/django/guide/optimizer#custom-polymorphic-solution

**Comment by bellini666** [comment]
@pcraciunoiu I think so, if not please let me know :)

**Comment by pcraciunoiu** [comment]
I believe I'm still seeing this issue on the latest 0.65 release.

In my mutation, if I return an interface, the typename on the relay ID of the object is resolved correctly.
But if I return a union, it just picks the first type from the union to base64-encode the ID.

I could try to set up an example if that's required, but that's the gist of the issue. Interface typename resolution works, union doesn't.

**Comment by pcraciunoiu** [comment]
@bellini666 here is a full setup:

```python
from typing import Annotated, Optional, Union
import strawberry, strawberry_django
from django.db.models import Model, CharField


class FruitModel(Model): 
    type = CharField(max_length=10)


@strawberry.interface
class Fruit(strawberry.relay.Node):
    type: str

    @classmethod
    def resolve_type(cls, value: models.TaskTemplate, info: strawberry.Info, parent_type) -> str:
        if value.type == "Apple":
            return "Apple"
        elif value.type == "Banana":
            return "Banana"
        raise TypeError("Invalid fruit type")


@strawberry_django.type(FruitModel, fields=["type"])
class Apple(Fruit):
    pass

@strawberry_django.type(FruitModel, fields=["type"])
class Banana(Fruit):
    pass


FruitUnion = Annotated[Union[Apple, Banana], strawberry.union("FruitUnion")]


@strawberry.type
class Queries:
    @strawberry.field
    def fruit(self, info: Info) -> FruitUnion:
        return FruitModel(type="Banana")

```


```graphql
query Fruit {
  fruit {
    __typename
    ... on Fruit {
      type
    }
  }
}
```

And the output is:

```json
{
  "data": {
    "fruit": {
      "__typename": "Apple",
      "type": "Banana"
    }
  }
}
```

If I change the return type from `FruitUnion` to `Fruit`, the `resolve_type` method gets called. It DOES NOT get called for the union.

This may be a strawberry bug, not a strawberry-django one, but I'm not sure.

**Comment by bellini666** [comment]
@pcraciunoiu you probably need to implement `is_type_of` in your classes and reject based on your rules. This is how it gets called: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/union.py#L172-L172

You can also use [cast](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/types/cast.py#L18-L18) from strawberry in this case, inside your resolver.

We probably need to document both of those in the strawberry docs.

Can you open an issue about this at strawberry itself? As this is not completely related to strawberry-django, as it could also happen with other integrations (e.g. pydantic)

**Comment by pcraciunoiu** [comment]
Thanks. That worked and I filed this with updated code here:
https://github.com/strawberry-graphql/strawberry/issues/3980
