### ISSUE TITLE
Add built-in support for List[]  django model properties

### ISSUE THREAD

**Issue by brentpicasso** [strawberry-graphql/strawberry-django#200]
Add built-in support for List[]  django model properties

- [ ] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

In our Django model we have a field defined as an ArrayField of chars:

```fields = ArrayField(models.CharField(max_length=150), null=True)```

Strawberry gives this error:
```NotImplementedError: GraphQL type for model field 'fields' has not been implemented```

Which likely needs a custom resolver like this

```
@strawberry.django.field
def fields(self, root: MyObject, info: Info) -> List[str]:
    return root.fields
```

This issue tracks the enhancement of strawberry-graphql-django to support his data type natively.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/200">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/200/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/200/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Just a note in here when implementing this: An array field can contain another array field, so for example `ArrayField(CharField)` should generate `List[str]` and `ArrayField(ArrayField(CharField))` should generate `List[List[str]]` and so on
