### ISSUE TITLE
self referencing Parent relation has pagination if type has it

### ISSUE THREAD

**Issue by hvdklauw** [strawberry-graphql/strawberry-django#252]
I have a category type:
```python

@strawberry.django.type(models.Category, pagination=True)
class Category:
    id: auto
    name: auto
    slug: auto
    parent: "Category"
    children: List["Category"]

```

The graphql then adds pagination to the parent relation, which makes no sense, the children it does make sense for.

## Describe the Bug

If the type is a single instance it should not have pagination by default.

## System Information

 - Operating system: Mac
 - Strawberry version (if applicable): 0.176.0

## Additional Context

I can fix it like this:
```python

@strawberry.django.type(models.Category, pagination=True)
class Category:
    id: auto
    name: auto
    slug: auto
    parent: "Category" = strawberry.django.field(pagination=False)
    children: List["Category"]

```

but that shouldn't be needed imho.

Should also note that filters and order are not passed to the parent relation!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/252">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/252/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/252/pledge.svg">
</picture>
</a>

**Comment by hvdklauw** [comment]
I am on 0.9.4 and yes, filters and order are not shown, pagination still is.

**Comment by bellini666** [comment]
@hvdklauw oh, I see. You are probably right.

Do you want to try to open a PR for this? Otherwise I'll try to fix this in the weekend

**Comment by hvdklauw** [comment]
I'll give it a go

**Comment by hvdklauw** [comment]
Ok, was writing tests and was wondering if [get_pagination](https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/strawberry_django/pagination.py#L42) should return None for fields like that.

```python

def test_pagination_on_related_field_definition():
    from strawberry_django.fields.field import StrawberryDjangoField

    group_field = StrawberryDjangoField(type_annotation=StrawberryAnnotation(Group))
    assert group_field.get_pagination() is not None
    assert User._type_definition.get_field("group").get_pagination() is None

```

**Comment by hvdklauw** [comment]
https://github.com/hvdklauw/strawberry-graphql-django/commit/125789984e2a23c643730c962aa774fd3126532c is what I made of it.

By returning UNSET in get_pagination it automatically won't add the arguments.

The thing is, now I think we also need to do this in filters and ordering to keep it consistent. Also couldn't find tests for those two in relation to not adding filters/order to those kind of fields.

**Comment by hvdklauw** [comment]
@bellini666 What do you think? should get_pagination (and thus get_filters and get_order) return UNSET when self.is_list is False or should just the arguments function not add arguments in those cases?
