### ISSUE TITLE
`DjangoPermissionExtension` does not support Channels requests. 

### ISSUE THREAD

**Issue by nrbnlulu** [strawberry-graphql/strawberry-django#330]
On Channels requests the context is a `dict` so you'll get an `AttributeError`.
https://github.com/strawberry-graphql/strawberry-graphql-django/blob/3a3a66e236acbc54ad7079ecfa2b92508f3ad60c/strawberry_django/permissions.py#L330

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/330">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/330/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/330/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
That's actually a general strawberry issue. Subscriptions doesn't support field extensions currently :(

**Comment by bellini666** [comment]
Hrm, I remember it not being supported, but maybe that changed? =P

Will take a look at the PR you opened

**Comment by bellini666** [comment]
> I think you are right `resolve_async` must return a coroutine and for subscriptions you need to return an async generator. I'll need to dig dipper to tell.

The extension can probably check the "before" permissions (i.e. the global and root permissions), but the "after" ones (i.e. retval) are more complicated because there isn't a single return value for those.

**Comment by bellini666** [comment]
This should be fixed in https://github.com/strawberry-graphql/strawberry/releases/tag/0.240.0

Please let me know if that's not the case
