### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jeemyeong** [strawberry-graphql/strawberry-django#364]
## Describe the Bug

Error Maximum recursion depth exceeded has occurred when I use `DjangoOptimizerExtension`

## System Information

 - Operating system: OSX 13.5.1 (22G90)
 - Strawberry version (if applicable):  
strawberry-graphql==0.207.0
strawberry-graphql-django==0.17.1

## Additional Context
<img width="1234" alt="image" src="https://github.com/strawberry-graphql/strawberry-graphql-django/assets/13030735/0384b4c3-18cd-49e9-81ff-c23fa102b7f4">

---

If needed, I'll prepare sample codes that can reproduce these symptoms

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/364">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/364/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/364/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hi @jeemyeong ,

Indeed it would be nice if you could provide a reproduction example, or at least more details about the issue, like its traceback.

**Comment by jeemyeong** [comment]
Hi @bellini666 :)
Thank you for the response.

```python3
# https://github.com/jeemyeong/strawberry-django-bug-report/blob/main/mysite/polls/models.py#L6-L8
class Question(models.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_question_text = self.question_text
        self.__original_pub_date = self.pub_date
```


This code is an extension of the Django tutorial with four additional lines.
Modifying the constructor of a Django model to add custom fields like this can lead to the occurrence of that error.

<img width="813" alt="image" src="https://github.com/strawberry-graphql/strawberry-graphql-django/assets/13030735/1cfcc9d1-9f5f-4743-8e0b-faacc4af5de1">

**Comment by pfcodes** [comment]
@jeemyeong -- how did you resolve this? I'm running into it too

**Comment by jeemyeong** [comment]
> @jeemyeong -- how did you resolve this? I'm running into it too

I decided to give up using the DjangoOptimizerExtension and directly optimized resolvers using dataloader.

**Comment by patrick91** [comment]
@pfcodes can you still reproduce it?
