### ISSUE TITLE
Have the DjangoOptimizerExtension also handle the Nested Filtering and Ordering edge cases.

### ISSUE THREAD

**Issue by NT-Timm** [strawberry-graphql/strawberry-django#378]
Queries with Nested Filters and Orders in them are not optimized. Which can cause a lot of unneeded extra query calls.

[Here](https://github.com/blb-ventures/strawberry-django-plus/issues/192#issuecomment-1616692730) @bellini666 asked @vitosamson to put up an issue for this. But I saw none here so here's mine.

I'm a bit short on time but I'll post an example tomorrow.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/378">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/378/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/378/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
This was resolved by https://github.com/strawberry-graphql/strawberry-django/releases/tag/v0.44.0
