### ISSUE TITLE
Documentation/Contributing: (pyenv?) Impossible to `make serve-docs` without installing additional packages: `mkdocs-material mkdocstrings mkdocs-minify-plugin mkdocs-markdownextradata-plugin`

### ISSUE THREAD

**Issue by thepapermen** [strawberry-graphql/strawberry-django#391]
For me (running pyenv in bash, Ubuntu) the `make serve-docs` section command doesn't work out of the box. Even though there are proper dev dependencies in the `pyproject.toml/[tool.poetry.group.dev.dependencies]`.

I needed to manually install these python packages:
`pip install mkdocs-material mkdocstrings mkdocs-minify-plugin mkdocs-markdownextradata-plugin`.

## System Information

 - Operating system: Ubuntu 20.04 (Elementary OS 6 Jólnir)

P.S.
There is `factory-boy` in `pyproject.toml` dev dependencies, but it looks like the tests are using `faker`  exclusively .

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/391">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/391/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/391/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Closing this as we don't host our docs with mkdocs anymore
