### ISSUE TITLE
Interface optimization hints doesn't get applied to all implementations

### ISSUE THREAD

**Issue by SafaAlfulaij** [strawberry-graphql/strawberry-django#420]
## Describe the Bug

_Note: all the following is pseudo code._

Given the following models:
```python
class BaseModel(models.Model):
    creation_user = models.ForeignKey("User", related_name="+", on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Pizza(BaseModel):
    title = models.CharField(max_length=20)


class Order(BaseModel):
    notes = models.CharField(max_length=20)
```

And the fields:
```python
@strawberry.django.interface(models.BaseModel)
class BaseRecord:
    created_by: "User" = field(select_related=['creation_user'])

@strawberry.django.field(models.Pizza)
class Pizza(BaseRecord, relay.Node):
    name: str

@strawberry.django.field(models.Order)
class Order(BaseRecord, relay.Node):
    notes: str
```

When querying pizza objects like so:
```qql
{
  pizzaObjs {
    createdBy { username }
  }
}
```
Optimization hints are applied (`select_related`).

But when querying order objects like so:
```qql
{
  orderObjs {
    createdBy { username }
  }
}
```
Optimization hints are not applied.

After debugging, it seems an issue around these lines:
https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/strawberry_django/type.py#L350-L366

Where the first implementation (`Pizza`) would get the `created_by` field defined, and `origin_django_type` set.
When the next implementation (`Order`) tries to get the `created_by` field defined, it does but as the field has defined `origin_django_type`, it tried to recreate the field (else clause) and ignore all the hints.

## System Information

 - strawberry-graphql-django: 0.23.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/420">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/420/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/420/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hi @SafaAlfulaij ,

The optimizer has gone through major changes recently. Is this still an issue in the latest release?

**Comment by bellini666** [comment]
Going to close this issue as it's most likely to have been fixed already. Please let me know if not so I can reopen it again
