### ISSUE TITLE
lookups doesn't accept null

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry-django#459]
when defining a query filter like:

```
query {
  users(filter: {username: {contains: null}}){
  }
}
```

the query fails with with: "Cannot use None as a query value" except for some filters like exact. And for exact this is a spec violation:

filters shall accept Unset or None to not filter

This bug causes errors when testing with schemathesis.
PR follows

## System Information

 - Strawberry version (if applicable): 0.29

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/459">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/459/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/459/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Fixed by https://github.com/strawberry-graphql/strawberry-django/pull/478

**Comment by devkral** [comment]
good idea, thank you
