### ISSUE TITLE
Document the export_schema command

### ISSUE THREAD

**Issue by thclark** [strawberry-graphql/strawberry-django#463]
## Feature Request Type

- Documentation

## Description

I was figuring out how to export my schema, since the new version of graphiql doesn't seem to allow you. It was a bit of a struggle. With graphene there was a management command to do it; and the penny dropped that this should have the same.

Little did I know that there was already an `export_schema` command. Let's put it in the docs!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/463">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/463/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/463/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@brunodantas we haven't document how to export from django, strawberry's default export command won't work with strawberry django 😊

**Comment by Ckk3** [comment]
Hi, I will create a PR to add this to the docs!

**Comment by Ckk3** [comment]
PR created! Please let me know if this any changes is necessary.

**Comment by bellini666** [comment]
Fixed by https://github.com/strawberry-graphql/strawberry-django/pull/546
