### ISSUE TITLE
OneToManyInput saves and runs validation on foreign key

### ISSUE THREAD

**Issue by keithhackbarth** [strawberry-graphql/strawberry-django#487]
## Example type:

```
@strawberry_django.input(Fruit)
class FruitInputPartial(PermissionMixin):
    id: auto
    location: auto
```

## Example mutation

```
            mutation PatchFruit {
                patchFruit(data: {id: 1, location: {set: 1}}) {
                    id
                    location { id }
                }
            }
```

## Expected

Only the fruit model receives clean and save. 1 database save operations

## Actual

Both the model and relation receive clean and save. 2 database save operations

## Additional Context

The reason this is painful is because of performance concerns. But also if paired with a library such as `django-simple-history` it creates a bunch of empty saves in foreign relationships.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/487">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/487/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/487/pledge.svg">
</picture>
</a>

**Comment by keithhackbarth** [comment]
@bellini666 - I can volunteer some time to write some tests and PR if you think is worthy of a fix. Do you know of another way to do it in the meantime?

I also noticed that this case seems to be broken:

```
@strawberry_django.input(Fruit)
class FruitInputPartial(PermissionMixin):
    id: auto
    location_id: ID

            mutation PatchFruit {
                patchFruit(data: {id: 1, locationID: 1}) {
                    id
                    location { id }
                }
            }
```

Expected: Updates location or throws an error
Actual: Does nothing

**Comment by bellini666** [comment]
> @bellini666 - I can volunteer some time to write some tests and PR if you think is worthy of a fix. Do you know of another way to do it in the meantime?

It surely is. And contributions are always very welcomed! 😊 

Feel free to ping me either here or at our [discord](https://strawberry.rocks/discord) channel if you need help with anything!
