### ISSUE TITLE
get_queryset() is not called

### ISSUE THREAD

**Issue by alimony** [strawberry-graphql/strawberry-django#488]
I'm trying to add a `.get_queryset()` class method to one of my types, but it is never called when querying. I just put a print on top of the method and it never happens. Fields on the type behave normally so I know the type is in use.

I can't get even the simple example from the docs to work:

```python
@strawberry_django.type(models.Fruit)
class Berry:

    @classmethod
    def get_queryset(cls, queryset, info, **kwargs):
        return queryset.filter(name__contains="berry")
```

What could be going on here?

I'm on version 0.28.2.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/488">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/488/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/488/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hi @alimony ,

Can you provide a MRE or at least give more information about how you are using using that type? Because there are some differences between using it directly on a root type (e.g. `Query`) or nested inside another type.

**Comment by alimony** [comment]
It looks something like this:

```python
@strawberry_django.type(
    Customer,
    filters=CustomerFilter,
    fields=[
        "name",
        ...
    ],
)
class CustomerType:
    name: auto
    org: OrgType

    @classmethod
    def get_queryset(
        cls, queryset: QuerySet[Customer], info: Info, **kwargs
    ) -> QuerySet[Customer]:
        return queryset.filter(...)
```

(Edited for NDA reasons.)

I can make a proper test case next week if needed.

**Comment by bellini666** [comment]
@alimony I mean, some examples of where that `CustomerType` is used.

For example, is is used in a root query like this?

```python
@strawberry.type
class Query:
    customers: list[CustomerType] = strawberry_django.field()
```

Or in a nested django type:

```python
@strawberry_type.type(SomeModel)
class SomeModelType:
    customers: list[CustomerType] = strawberry_django.field()

    # or like this
    @strawberry_django.field
    def customers(self) -> list[CustomerType]:
        ...
```

**Comment by alimony** [comment]
It's at the root, if I understand your question correctly. At the top level I have something like this:

```python
@strawberry.type
class Query:
    customers: CustomerType | None = strawberry_django.field(extensions=[auth_required])

...

schema = strawberry.Schema(
    query=Query,
    mutation=Mutation,
    extensions=schema_extensions,
)
```

and then this:

```python
@strawberry_django.type(
    Customer,
    filters=CustomerFilter,
    fields=[
        "name",
        ...
    ],
)
class CustomerType:
    name: auto
    org: OrgType
    ...

    @classmethod
    def get_queryset(cls, queryset: QuerySet[Customer], info: Info, **kwargs) -> QuerySet[Customer]:
        print('calling custom get_queryset')  # this never gets called
        return queryset.filter(...)
```

**Comment by bellini666** [comment]
Hey @alimony ,

I'm trying to replicate the issue in here but it is working correctly on my tests.

Take a look at this test for example: https://github.com/strawberry-graphql/strawberry-django/commit/7b5ee33c9f1c9692611ac7c07cb1d8156f74e13c#diff-723b95803cbfa95b72fb2bc64e3000c86c7cf4920592b4dec6e15cc2ae08e821R167 . I defined it just like your example and `get_queryset` is being called (the test passes ok)

The only major difference I can see is that you have `extensions=[auth_required]` defined. Is it doing something to the field that could cause its behaviour to change?

**Comment by alimony** [comment]
@bellini666 How can I reopen this issue? I'm running into this again, but this time using a custom field class. For example, something like:

```python
class CustomField(StrawberryDjangoField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print("init")

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        print("get_queryset")
        return queryset

@strawberry_django.type(
    MyClass,
    field_cls=CustomField,
    ...
)
class MyClassType:
    ...
```

My output shows that `.__init__()` is called, but `.get_queryset()` is never called, when using this type in any query.

**Comment by bellini666** [comment]
Hi @alimony ,

Indeed, the filter might now have its `get_queryset` called, depending on how it is solving itself. Please take a look at [get_result](https://github.com/strawberry-graphql/strawberry-django/blob/main/strawberry_django/fields/field.py#L150) to check how it works.

Either way, since this issue is related to a type's `get_queryset,` would you mind opening another issue to register yours? It would be nice if you could also add a reproduction example together with it
