### ISSUE TITLE
Auto Enums does not works with gettext_lazy choice values

### ISSUE THREAD

**Issue by fabien-michel** [strawberry-graphql/strawberry-django#489]
When a django choices is defined using gettext_lazy strings, it makes the "description is a string" check fail in 
[graphql.type.definition.GraphQLEnumValue](https://github.com/graphql-python/graphql-core/blob/430ee891a52d239adadf133d873fdca2a3fe009b/src/graphql/type/definition.py#L240)

The check `is_description(description)` return False if description is of type `django.utils.functional.lazy.<locals>.__proxy__`

### Context

Strawberry django's settings 
```python
STRAWBERRY_DJANGO = {
    "GENERATE_ENUMS_FROM_CHOICES": True,
}
```

### Failing test

in `tests/test_enums.py` 

Add choice with `gettext_lazy` description

```python
from django.utils.translation import gettext_lazy

class Choice(models.TextChoices):
    """Choice description."""

    A = "a", "A description"
    B = "b", "B description"
    C = "c", "C description"
    D = "d", gettext_lazy("D description")
```    

### Possible fix

As a fix I would suggest to change [this line](https://github.com/strawberry-graphql/strawberry-django/blob/17720f324e8876c41557d3cfb5ece45d6d59c880/strawberry_django/fields/types.py#L463) from:
```python
c[0]: EnumValueDefinition(value=c[0], description=c[1])
```

to
```python
c[0]: EnumValueDefinition(value=c[0], description=str(c[1]))
```

It would also be possible to change [this line](https://github.com/strawberry-graphql/strawberry-django/blob/17720f324e8876c41557d3cfb5ece45d6d59c880/strawberry_django/fields/types.py#L448) from

```python
choices = cast(List[Tuple[Any, str]], model_field.choices)
```

to 

```python
choices = [c[0]: str(c[1]) for c in model_field.choices]
```

I can propose a PR if you agree with one of these changes.

Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/489">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/489/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/489/pledge.svg">
</picture>
</a>

**Comment by sdobbelaere** [comment]
@fabien-michel I like this discovery about this setting.  - and indeed I have the same issue as yourself.  I'm sure @bellini666 would appreciate a PR for it. I know I would.

**Comment by fabien-michel** [comment]
I have a concern about the fixes I proposed. Adding `str()` will trigger the translation mechanism, and because the enum loading is done at GraphQL schema init on python code load, it voids the laziness benefit of using gettext_lazy...
I'm not sure if there is a better solution.

**Comment by bellini666** [comment]
I agree that's possibly the only solution right now, and as @sdobbelaere said, I would indeed appreciate a PR for it :)

For a better solution I think we would need to introduce some kind of "laziness" support on strawberry itself for loading descriptions that doesn't rely on django. I'll try to think about something to better solve this in the future... Any ideas here @patrick91 ?
