### ISSUE TITLE
Enum values in mutation input causes ValidationError

### ISSUE THREAD

**Issue by cngai** [strawberry-graphql/strawberry-django#491]
When calling a mutation with an input argument that accepts an enum value, instead of saving the enum value to the field, the object attempts to save the enum itself, thus throwing a Django ValidationError `"Value 'ExampleEnum.VALUE' is not a valid choice."`.

### Example
```python
# models.py
class Fruit(models.Model):
    status = models.CharField(max_length=16, choices=[("FRESH", "FRESH"), ("ROTTEN", "ROTTEN"), ("UNDERRIPE, "UNDERRIPE")], ...)


# settings.py
STRAWBERRY_DJANGO = {
    "GENERATE_ENUMS_FROM_CHOICES": True,
}


# schema.py
@strawberry_django.type(Fruit, fields="__all__")
class FruitType:
    pass

@strawberry_django.input(Fruit, partial=True)
class FruitInputPartial:
    id: auto
    status: strawberry.auto

@strawberry.type
class Mutation:
    patch_fruit: FruitType = strawberry_django.mutations.update(FruitInputPartial)


# GraphQL Mutation
mutation PatchFruit {
    patchFruit(data: {"id": 1, "status": FRESH}) {
        status
    }
}
```
In the example above, Strawberry would auto-generate a `FruitStatusEnum` for me since the `Fruit.status` model field has defined `choices`. The input type for my `FruitInputPartial.status` field is auto-resolved as `FruitStatusEnum`. However, when I call the mutation defined above, it tries saving the status field as `FruitStatusEnum.FRESH` as opposed to `FruitStatusEnum.FRESH.value`, which is why I get the `django.core.exceptions.ValidationError: {'status': ["Value 'FruitStatusEnum.FRESH' is not a valid choice."]}` error.

### Reproduction Steps
1. For [tests/test_input_mutations.py/test_input_update_mutation](https://github.com/strawberry-graphql/strawberry-django/blob/main/tests/test_input_mutations.py#L381), override the test settings to set `GENERATE_ENUMS_FROM_CHOICES` to be `True` by adding the`@override_settings` decorator to the test (shown below).
```python
from django.test import override_settings
from strawberry_django.settings import strawberry_django_settings

# Add this decorator to the test function
@override_settings(
    STRAWBERRY_DJANGO={
        **strawberry_django_settings(),
        "GENERATE_ENUMS_FROM_CHOICES": True,
    },
)
@pytest.mark.django_db(transaction=True)
def test_input_update_mutation(db, gql_client: GraphQLTestClient):
    query = """
    mutation CreateIssue ($input: IssueInputPartial!) {
        updateIssue (input: $input) {
            ...
```
2. Run the test and print out the response: `print(res.data)`.

**Expected:** The test should pass and `Issue.kind` should have a value of `"f"` due to the update mutation.
**Actual:** The test will fail and you will observe the following response:
```
{'updateIssue': {'__typename': 'OperationInfo', 'messages': [{'kind': 'VALIDATION', 'field': 'kind', 'message': "Value 'ProjectsIssueKindEnum.f' is not a valid choice."}]}}
```

### Potential Fix
If we pass in an enum alue, we can correctly parse the input type by adding an if-statement in the `mutations/resolvers.py/parse_input` function as follows:
```python
if isinstance(data, enum.Enum):
    return data.value
```

## Additional Context

The current workaround is to change the `strawberry.auto` type for my input field to be `str | None`, but then I lose the strong typing for my client-side app.

Let me know if you need any more information or if you'd like me to submit a PR. Thanks!

## System Information

 - Operating system: macOS Sonoma
 - Strawberry Django version (if applicable): 0.32.2

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/491">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/491/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/491/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @cngai ,

As I said on discord, I usually use [django-choices-field](https://github.com/bellini666/django-choices-field) which automatically integrates with strawberry: https://strawberry-graphql.github.io/strawberry-django/integrations/choices-field/, so I was not really aware of this =P

I think your "Potential Fix" is the way to go here! Do you want to try to open a PR with that solution? Let me know if I can help you with that :)

**Comment by cngai** [comment]
Thanks for taking a look @bellini666 ! I'll put up a PR in the next few days. Appreciate the help!
