### ISSUE TITLE
Apollo Sandbox doesn't update debug toolbar

### ISSUE THREAD

**Issue by catgirlinspace** [strawberry-graphql/strawberry-django#514]
## Describe the Bug

Sending GraphQL requests from Apollo Sandbox (when configured with the `graphql_ide` parameter) does not update the debug toolbar like it does for GraphiQL. 

GraphiQL properly updates the debug toolbar:
<img width="1167" alt="image" src="https://github.com/strawberry-graphql/strawberry-django/assets/13684891/675cf5ef-9f51-4fa0-90a2-1e7cd97ee9f8">
Apollo Sandbox does not:
<img width="1181" alt="image" src="https://github.com/strawberry-graphql/strawberry-django/assets/13684891/1c80d686-3baf-4328-b594-e0d6cbe7929a">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/514">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/514/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/514/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hrm, we have a custom subclass of the debug toolbar middleware in here (https://github.com/strawberry-graphql/strawberry-django/blob/main/strawberry_django/middlewares/debug_toolbar.py#L165), which in theory should not be graphiql specific.

Maybe we need to tweak it...

**Comment by bellini666** [comment]
Think I found the issue, the fix will be included in the next release
