### ISSUE TITLE
Ability to use custom StrawberryDjangoField class for relay connections and nodes

### ISSUE THREAD

**Issue by stygmate** [strawberry-graphql/strawberry-django#517]
We can pass a custom StrawberryDjangoField via `field_cls` parameter to types but not to relay connections and nodes.
Is it possible to add this ?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/517">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/517/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/517/pledge.svg">
</picture>
</a>

**Comment by stygmate** [comment]
@bellini666 Thank you  !  👍

**Comment by stygmate** [comment]
@bellini666 I need all my fields to use a custom class based on StrawberryDjangoField. My goal is to have the automatic addition of certain extensions (including authentication) and automatic alterations of field descriptions. However, as it stands, this means passing the custom class to all my types and field definitions for queries and mutations. It's quite repetitive. It can be a game changer to have a way to set a default class (settings). It would involve some editing throughout the Strawberry-Django code, but it could really simplify things in my case.

**Comment by bellini666** [comment]
Hey @stygmate ,

Hrm, I'm open to suggestions! 😊

In the meantime, something you can do is something like:

```python
import functools


my_custom_type = functools.partial(strawberry_django.type, field_cls=MyCustomFieldCls)
```

That should even type it correctly. If not, you can do something like:

```python
from typing import TYPE_CHECKING
import functools


IF TYPE_CHECKING:
    my_custom_type = strawberry_djang.type
else:
    my_custom_type = functools.partial(strawberry_django.type, field_cls=MyCustomFieldCls)
```

And use that decorator for now
