### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by moritz89** [strawberry-graphql/strawberry-django#527]
I don't know if this has been said enough @bellini666, but the Django integration and especially the query optimizer are an amazingly well implemented. Just had the issue of debugging N+1 query problems and using the provided docs and the hint functionality and it all just works. Hope all the Strawberry maintainers have a great summer weekend.

Feel free to close / delete this "issue".

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/527">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/527/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/527/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
I'm really glad that you enjoy it and find it useful. Not gonna lie, this just made my day today 😊 

Have a great weekend you too!
