### ISSUE TITLE
`DjangoOptimizerExtension` can't hand `order_with_respect_to` tuples with using `OrderedModel`

### ISSUE THREAD

**Issue by Eraldo** [strawberry-graphql/strawberry-django#536]
## Describe the Bug

When a Django model has the `order_with_respect_to` property set to a tuple of fields, the `DjangoOptimizerExtension` throws the following error:
```
"message": "maximum recursion depth exceeded in comparison",
```

Update:
Only happens if the model inherits from: `OrderedModel`: https://github.com/django-ordered-model/django-ordered-model

Reproduction: https://github.com/Eraldo/strawberry-django-optimizer-infinite-recursion-mre

## System Information

 - Operating system: OSX 14.5 (23F79)
 - Strawberry version (if applicable):
```
strawberry-graphql-django = "^0.41.1"
strawberry-graphql = "^0.232.2"
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/536">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/536/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/536/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Closing this as it is not actually an issue with the optimizer, but actually with `ordered-models` itself, and triggers when the optimizer does `QS.only(...)`. See https://github.com/django-ordered-model/django-ordered-model/issues/297

While that issue is not fixed, this can be avoided by passing `enable_only_optimization=False` to the `DjangoOptimizerExtension`
