### ISSUE TITLE
Broken interfaces with optimiser extension

### ISSUE THREAD

**Issue by ManiacMaxo** [strawberry-graphql/strawberry-django#550]
Querying interfaces crashes when using the optimiser extension caused by #537.

## Describe the Bug
Any field that is an interface will raise an assertion error when queried. `disable_optimizations=True` has no effect. This is caused by the new implementation which uses `schema.schema_converter.from_object` that only supports concrete objects - not interfaces.

## System Information

 - Operating system: any
 - Strawberry version (if applicable): >=0.42.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/550">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/550/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/550/pledge.svg">
</picture>
</a>

**Comment by ManiacMaxo** [comment]
I've implemented a possible solution [here](https://github.com/ManiacMaxo/strawberry-django/commit/93074cd05d9a3731ee3385480a8bb7a6cf662a1b). Another possibility is to ignore interface types altogether during optimisation

**Comment by bellini666** [comment]
Hey @ManiacMaxo ,

Thanks for that!

I think your solution is great! Would you like to open a PR for that?

**Comment by bellini666** [comment]
Hey @ManiacMaxo ,

I tried writing a test using interfaces, but everything passed: https://github.com/strawberry-graphql/strawberry-django/pull/554

What should we do to reproduce the issue to go together with your fix to make sure that doesn't regress in the future?

**Comment by ManiacMaxo** [comment]
Hi @bellini666,

Unfortunately I couldn't recreate the issue without using django-polymorphic (which is why I'm using interfaces) since it returns the interface type's model which can be cast into all concrete types
