### ISSUE TITLE
Suggestion: Refactoring of optimizer code

### ISSUE THREAD

**Issue by stygmate** [strawberry-graphql/strawberry-django#573]
The current optimizer code seems unreadable to me without extensive knowledge of Strawberry and Django.

Refactoring by dividing this code into more functions with a description and (perhaps) renaming the variables can help to better understand, maintain and debug it.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/573">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/573/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/573/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Yeah, I agree with you!

I have started doing some refactoring for the past commits when I had to change it, but there's still some work to be done
