### ISSUE TITLE
values() and optimizer hints

### ISSUE THREAD

**Issue by tasiotas** [strawberry-graphql/strawberry-django#574]
I am trying to make this query optimizer friendly.
```python
object.reactions.all().values("type").annotate(authors=ArrayAgg("author__full_name", ordering="-date_created"))
```

As you can see I have grouped reactions by type using values().
Optimizer is accepting hints like `only`, `select_related`, `prefetch_related` and `annotate`.

I did use annotate, but because I cannot group it before with `values("type")`, I am getting wrong results.

Is there any way to build Query Expression that can combine `value()` and `annotate()` ?

This is my current, not working, field with annotation.
```python
@strawberry.django.field(
        prefetch_related=["reactions", "reactions__author"],
        annotate={"authorsss": ArrayAgg("author__full_name", ordering="-date_created")},
    )
    def reactions_summary(self, info) -> JSON:
        return reactions_summary_long(self, info.context.request.user)
```

There is similar https://github.com/strawberry-graphql/strawberry-django/issues/549 with annotations

Thank you

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/574">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/574/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/574/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
I have been thinking about this, but I'm not actually sure on what is the proper solution...

Allowing to do `.values()` in the queryset messes with it, and it can have unwanted side effect in the remaining resolution of the type itself.

2 things comes to my mind here:

1) Convert it to a `prefetch related`, like this:

```python
    @strawberry.django.field(
        prefetch_related=[
            "reactions",
            "reactions__author",
            lambda info: Prefetch(
                "authors",
                queryset=Author.objects.only("full_name").order_by("-date_created")
                to_attr="authorsss",
            )
        ],
    )
    def reactions_summary(self, info) -> JSON:
		# change this function to consider that you have an `authorsss`
        # inside it, and do `authors_names = [a.full_name for author in obj.authorsss]
        return reactions_summary_long(self, info.context.request.user)
```

2) Use a [dataloader](https://strawberry.rocks/docs/guides/dataloaders) to solve this specific situation, where you can handle more complex cases in an easier way

Let me know what you think? Does any of those 2 solves your issue? Or do you have a reason to really have to have it as an `ArrayAgg`?

**Comment by tasiotas** [comment]
Hi,

Thank you for looking into it and trying to implement values().

In fact I am already using your first solution with Prefetch. ArrayAgg is not necessary at all, I don't even remember how did I come up with that. Seems like development and prod implementation are two different things :)

I am still yet to try to use dataloaders for my custom queries, good to know we have it as an option.

Thanks!
