### ISSUE TITLE
Query optimizer raises FullResultSet exception when using PostgreSQL

### ISSUE THREAD

**Issue by he0119** [strawberry-graphql/strawberry-django#576]
## Describe the Bug

Consider a schema like the following.

```python
class Topic(models.Model):
    id = models.AutoField("ID", primary_key=True, auto_created=True)
    title = models.CharField("Title", max_length=200)

class Comment(models.Model):
    id = models.AutoField("ID", primary_key=True, auto_created=True)
    body = models.TextField("Body")
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="comments"
    )

@strawberry_django.type(models.Topic)
class Topic(relay.Node):
    comments: strawberry_django.relay.ListConnectionWithTotalCount["Comment"] = (
        strawberry_django.connection()
    )


@strawberry_django.type(models.Comment)
class Comment(relay.Node):
    body: strawberry.auto

@strawberry.type
class Query:
    topics: strawberry_django.relay.ListConnectionWithTotalCount[Topic] = (
        strawberry_django.connection()
    )

schema = strawberry.Schema(
    query=Query,
    extensions=[DjangoOptimizerExtension],
)
```

When querying topic objects and also the last one comments:

```graphql
query topics {
  topics {
    edges {
      node {
        comments(last: 1) {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```
It will raise `FullResultSet` exception.

This error only occurs when using PostgreSQL, it works fine using SQLite.

## System Information

 - strawberry-graphql-django: 0.46.1

## Additional Context

Minimal Reproduce: <https://github.com/he0119/strawberry-django-error-repo>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/576">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/576/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/576/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hrmm that's interesting. I tested your reproduction and it seems to be caused when using last, because it forces a limit using `sys.maxsize` and that would cause an overflow on postgresql.

Working on a fix here
