### ISSUE TITLE
When the optional file field is used, an error will be reported when there are empty files in the query set

### ISSUE THREAD

**Issue by star2000** [strawberry-graphql/strawberry-django#58]
Error is thrown from here
https://github.com/django/django/blob/475cffd1d64c690cdad16ede4d5e81985738ceb4/django/db/models/fields/files.py#L40

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/58">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/58/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/58/pledge.svg">
</picture>
</a>

**Comment by star2000** [comment]
I avoid it like this
```python
from django.db.models.fields import files


class FieldFile(files.FieldFile):
    def _require_file(self):
        pass


class FileField(files.FileField):
    attr_class = FieldFile


class ImageFieldFile(files.ImageFieldFile):
    def _require_file(self):
        pass


class ImageField(files.ImageField):
    attr_class = ImageFieldFile

```

**Comment by star2000** [comment]
Is there a more elegant way?

**Comment by star2000** [comment]
> I avoid it like this
> 
> ```python
> from django.db.models.fields import files
> 
> 
> class FieldFile(files.FieldFile):
>     def _require_file(self):
>         pass
> 
> 
> class FileField(files.FileField):
>     attr_class = FieldFile
> 
> 
> class ImageFieldFile(files.ImageFieldFile):
>     def _require_file(self):
>         pass
> 
> 
> class ImageField(files.ImageField):
>     attr_class = ImageFieldFile
> ```


A more elegant way: 
```py
from django.db.models.fields.files import FieldFile

FieldFile._require_file = lambda self: None  # type:ignore[attr-defined]
```

**Comment by mnogokotin** [comment]
any fix for this? )

**Comment by Eraldo** [comment]
Also ran into this.
Current: `FileField` with `blank=True` gets resolved as required by `auto`!
Expected: `FileField` with `blank=True` gets resolved as optional by `auto`.
