### ISSUE TITLE
Filters in nested fields don't work

### ISSUE THREAD

**Issue by pfcodes** [strawberry-graphql/strawberry-django#589]
## Describe the Bug

When a filter is nested within two other objects, the filter doesn't do anything.

```
{
  allCreativeProfessions {
    edges {
      node {
        id
        individualCreatives {
          edges {
            node {
              creativeWorkPortfolioProjects(filters: { status: { exact: PUBLISHED}}) {
                edges {
                  node {
                    status
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

## System Information

 - Strawberry version : 0.46.2

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/589">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/589/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/589/pledge.svg">
</picture>
</a>

**Comment by NT-Timm** [comment]
Are you sure?
This should show all CreativeProfessions and all individualCreatives of those proffessions.
But only the creativeWorkPortfolioProjects that have the status PUBLISHED.

If you want to filter CreativeProfessions or individualCreatives you need to start the filters there and link the filters.

**Comment by pfcodes** [comment]
It turns out that a prefetch using the `to_attr` was breaking the filters. Mistake on my end.
