### ISSUE TITLE
FilterLookup filters has strange behavior when chaining them together.

### ISSUE THREAD

**Issue by pfcodes** [strawberry-graphql/strawberry-django#595]
## Describe the Bug

I'm trying to implement filters so theres always one fixed filter which is always set and then additional filters chained on top of it to drill down a set of results. So for example, say I want to filter for a person that has a profession of "driver" and in addition to driver they are also _both_ a mechanic and engineer. I would expect this to work:

```
filters: {
  professions: {
    id: { exact: "driver" },
    AND: {
      id: { inList: ["mechanic", "engineer"] },
    },
  },
}
 ```
 
 But it doesn't work at all... I tried doing this:
 
 ```
filters: {
  professions: {
    id: { inList: ["driver", "mechanic", "engineer"] },
  },
}
 ```
 
 But it gives me people who are driver OR mechanic OR engineer. I need the behavior to be driver AND mechanic AND engineer.
 

## System Information

 - Strawberry version (if applicable): 0.47.0

## Additional Context

I defined the filters with `FilterLookup`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/595">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/595/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/595/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
As we discussed the other day, this is something that strawberry doesn't support, meaning you have to rely on custom filtering for this.

Going to close this for now

**Comment by pfcodes** [comment]
Leaving this comment as a record for anyone that might be coming from Graphene/django-filters. This type of filtering behavior is known as a `[conjoined](https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter)` filter. I'll probably make a feature request on Strawberry to support it.
