### ISSUE TITLE
Test Query Client `asserts_errors` is counter intuitive

### ISSUE THREAD

**Issue by thclark** [strawberry-graphql/strawberry-django#602]
## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

In the `BaseGraphQLTestClient` (`/test/client.py`), there is an option `asserts_errors` which is by default `True`.

I'm finding this to be incredibly counterintuitive for two reasons:

1. It's not the job of a query client to decide what should be in the response (especially by default), this is the job of my test code ("separation of concerns").
2. It's named incorrectly. "Asserts Errors" implies it asserts that there ARE errors, not that there AREN'T.

I think this check should be removed. If it is kept, the name should be made explicit (`assert_no_errors`) and ideally made opt-in rather than opt-out. 

### Special concern

Is it typical for cases to arise in which errors would be returned *alongside* an otherwise valid response? Because if that's the case then I kind of understand why it's opt-out by default. Otherwise, testing for valid data response should be sufficient, AFAICT?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/602">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/602/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/602/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @thclark ,

Hrm, I do agree with your points here... Why did you close the issue though?
