### ISSUE TITLE
CUD mutation - partial Input

### ISSUE THREAD

**Issue by gfort-amarena** [strawberry-graphql/strawberry-django#619]
Hi,

I am struggling with the CUD mutation and the partial inputs, the schema does not detect at all that the fields are optional

```

class MyModel(models.Model):
    title = models.CharField()
    subtitle = models.CharField()

# I first tried this
@strawberry_django.input(MyModel, fields="__all__", partial=True)
class MyModelInput:
    pass

# then tried with this
@strawberry_django.partial(MyModel, fields="__all__")
class MyModelInputPartial:
   pass

# and this, also tried with 'auto'
@strawberry_django.partial(MyModel, fields="__all__")
class MyModelInputPartial:
   title: str | None
   subtitle: str | None

@strawberry_django.type(
    MyModel,
    fields="__all__",
)
class MyModelType:
    pass

@strawberry.type
class Mutation:
    update: MyModelType = strawberry_django.mutations.update(MyModelInputPartial)

```

I tried using NodeInput as well, nothing works, in the schema subtitle and title are always mandatory data inputs
I want to only input either title or subtitle without having to reset the other attribute.

Thanks for you help,

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/619">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/619/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/619/pledge.svg">
</picture>
</a>

**Comment by NT-Timm** [comment]
I think your issue is with the Django bit.
blank is by default False. And it determines in Django if a field is optional when used.

blank=True on the model Field makes it optional with:
```
@strawberry_django.input(MyModel, fields="__all__", partial=True)
class MyModelInput:
    pass
```

**Comment by bellini666** [comment]
Alongside with @NT-Timm's comment, a field would also be considered optional if it has a default value.

Based on that, I'm going to close this issue. But, if you think this is still an issue and we should solve it in another way, please comment so I can reopen it.
