### ISSUE TITLE
Ordering does not work properly with federation gateway

### ISSUE THREAD

**Issue by iamcrookedman** [strawberry-graphql/strawberry-django#625]
I'm not sure if this is a problem with this library but definitely the current ordering design doesn't work with @apollo/gateway.

The sort order depends on the order of the keys and when requesting the server directly it works as it should, but when requesting through the federation the order of the keys changes to alphabetical.
Perhaps the ordering body should be an array to avoid dependence on the order of the keys.
I understand that this is a big change in design but in this case we are dependent on how the dictionaries are implemented in one or another part of the system.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/625">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/625/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/625/pledge.svg">
</picture>
</a>

**Comment by najeeb-thalakkatt** [comment]
Same issue here

**Comment by bellini666** [comment]
Hi @iamcrookedman ,

Yeah, this is the same issue as this one: https://github.com/strawberry-graphql/strawberry-django/issues/615

I think the way to solve this will be to revamp the pagination stuff to use an array, just like you said

Going to close this as duplicated, to keep the related discussion in the same place :)
