### ISSUE TITLE
HasRetvalPerm - strings are treated as Iterable and returned as List insted of String

### ISSUE THREAD

**Issue by rickypag** [strawberry-graphql/strawberry-django#626]
## Describe the Bug

In our project we are using the class `HasRetvalPerm` to ensure object level permissions to our types.
An example of how we define a query is:

```
@strawberry_django.type
class MyType:
    my_string_field: Optional[str] = strawberry.field(
        resolver=lambda: "my_string",
        extensions=[HasRetvalPerm(MY_TYPE_PERMISSION)]
    )
```

However, when I run for example the following query

```
query {
   myType {
      myStringField
   }
}
```

the field is not resolved and instead I get this error:
`"String cannot represent value: ['m', 'y', '_', 's', 't', 'r', 'i', 'n', 'g']"`

What I assumed is happening is that the value is transformed into a list before being returned.

After digging a bit into the implementation, I realised that in the [_resolve_obj](https://github.com/strawberry-graphql/strawberry-django/blob/main/strawberry_django/permissions.py#L814) there is this check:
```
    def _resolve_obj(
        self,
        source: Any,
        user: UserType,
        obj: Any,
        *,
        info: Info,
    ) -> Any:
        context = perm_context.get()
        if context.is_safe:
            return obj

        if isinstance(obj, Iterable):
            return list(self._resolve_iterable_obj(source, user, obj, info=info))
```

Since `isinstance(obj, Iterable)` is True if obj is a string, the return value will be trasformed into a list.

### Expected behaviour
A string should not be treated as Iterable in this case

## System Information

 - Operating system:
 - Strawberry version (if applicable): 0.235.1
 - Strawberry Django version: 0.46.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/626">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/626/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/626/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hi @rickypag ,

Hrm, the main issue here is that `HasRetvalPerm` will check permissions against the "retval", which is expected to be a django model object.

Is there a reason why you are trying to use `HasRetvalPerm` in a field that returns a string? If that field is in a `DjangoType` parent, you could use [HasSourcePermission](https://strawberry.rocks/docs/django/guide/permissions#available-options) instead.

Will leave this issue open to understand more of your use case and understand if this is really an issue or not.

**Comment by rickypag** [comment]
Hi @bellini666,
Thank you for pointing this out. I was indeed using the wrong class permission and with HasSourcePerm I managed to make the type work as expected!

**Comment by bellini666** [comment]
@rickypag awesome, so I'm going to close this issue. Let me know if you find something else
