### ISSUE TITLE
TypeError: GraphQLView() received an invalid keyword 'subscriptions_enabled'. as_view only accepts arguments that are already attributes of the class.

### ISSUE THREAD

**Issue by thclark** [strawberry-graphql/strawberry-django#644]
## Describe the Bug

When using subscriptions in a view as [according to the docs here](https://strawberry.rocks/docs/django/guide/subscriptions), you update your urls.py to look like:

```py
urlpatterns = [
  ...
    path(
        'graphql/',
        AsyncGraphQLView.as_view(
            schema=schema,
            graphiql=settings.DEBUG,
            subscriptions_enabled=True,
        ),
    ),
    ...
]
```

However, this causes an error during testing:
```
TypeError: AsyncGraphQLView() received an invalid keyword 'subscriptions_enabled'. as_view only accepts arguments that are already attributes of the class.
```

**The same error occurs using `GraphQLView()` rather than `AsyncGraphQLView()`.**

## System Information

```
# from my pyproject.toml
strawberry-graphql = {version = "^0.246.2", extras = ["debug-server"]}
strawberry-graphql-django = "^0.49.0"
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/644">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/644/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/644/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @thclark ,

That keyword got removed from strawberry on https://github.com/strawberry-graphql/strawberry/releases/tag/0.245.0. We probably need to update the docs here as well, thanks for pointing that out.

Let me tag this as docs

(if by any chance you want to try to send a PR for this, feel free! otherwise I'll probably fix it by the weekend)

**Comment by thclark** [comment]
Thanks @bellini666 - love it when it's just a docs tweak :)

**Comment by patrick91** [comment]
Thank you @bellini666 for contributing to close this issue! ⭐

The rewards from this issue, totaling $40, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
