### ISSUE TITLE
Returning a Query type in a mutation's payload

### ISSUE THREAD

**Issue by rcybulski1122012** [strawberry-graphql/strawberry-django#655]
I have a `Query` type in my schema that defines some custom resolvers and uses `strawberry_django.field`/`strawberry_django.node` without providing resolver functions.

```python
@strawberry_django.type(SomeModel)
class SomeType:
    id: auto
    name: auto


@strawberry.type(name='Query')
class Query:
    some_type_query: SomeType = strawberry_django.field()

    @strawberry_django.field()
    def custom_resolver(self) -> bool:
        return True
```

I want to return a `Query` along with the mutation result, enabling the user to fetch whatever data they need in a single request. However, when I initialize a Query object, I must provide arguments.

```python
@strawberry.type
class MutationPayload:
    some_type: SomeType

    @strawberry_django.field(
    def query(self) -> Query:
        return Query()


@strawberry.type
class Mutation:
    @strawberry_django.mutation()
    def mutation_resolver(self) -> MutationPayload:
        some_model = SomeModel.objects.create(name="test")
        return MutationPayload(some_type=some_model)
```

```
{
  "data": null,
  "errors": [
    {
      "message": "Query.__init__() missing 1 required keyword-only argument: 'some_type_query'",
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "mutationResolver",
        "query"
      ]
    }
  ]
}
```

Is it possible to initialize the `Query` type without providing all the arguments? Or is there an easy way to provide the arguments to the query?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/655">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/655/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/655/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @rcybulski1122012 ,

This is something that is being discussed on https://github.com/strawberry-graphql/strawberry-django/issues/627

I am going to close this as duplicated, but be sure to check it as other users have shared some workarounds which you can use in the meantime.
