### ISSUE TITLE
New `PAGINATION_DEFAULT_LIMIT` pagination setting isn't used

### ISSUE THREAD

**Issue by SupImDos** [strawberry-graphql/strawberry-django#656]
## Describe the Bug

The recent release that included PR #642 introduced a new setting, `PAGINATION_DEFAULT_LIMIT`, which is mentioned in the [settings](https://strawberry.rocks/docs/django/guide/settings) and [pagination](https://strawberry.rocks/docs/django/guide/pagination#default-limit-for-pagination) documentation sections.

However, upon reviewing the PR and the codebase, it appears that `PAGINATION_DEFAULT_LIMIT` is not actually currently referenced or used anywhere! This suggests that the setting is currently non-functional and does not affect pagination behavior.

## Suggested Approach

We should either remove the `PAGINATION_DEFAULT_LIMIT` setting and its documentation, or implement its expected behaviour. Once the issue with is addressed, it would also be helpful to update the documentation to clarify that Relay pagination limits are controlled separately by the `relay_max_results` setting from the upstream `strawberry` package (if still applicable). This setting is documented in the [Relay configuration guide](https://strawberry.rocks/docs/types/schema-configurations#relay_max_results).

## System Information

 - Operating system: MacOS
 - Strawberry version (if applicable): 0.248.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/656">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/656/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/656/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
OMG such an oversight on my end 🤦

Thanks for the report, I'm going to fix this
