### ISSUE TITLE
Optimizer results are not used in case of one-to-many relations where just one object is used

### ISSUE THREAD

**Issue by diesieben07** [strawberry-graphql/strawberry-django#662]
## Describe the Bug
When you have a one-to-many relation in a model, so either a reverse lookup of a foreign key or a many to many field, the optimizer will prefetch it (good 👍). If the field in GraphQL however is declared as not returning a list or connection but just a single type, then the default resolver will use `QuerySet#first` / `QuerySet#get` to get the result, which will bypass the prefetched objects and issue new queries.

Example:
```python
class Project(models.Model):
  name = models.CharField(max_length=255)

class Issue(models.Model)
  project = models.ForeignKey(Project, related_name='issues')


@strawberry_django.type(Issue, name='Issue')
class IssueType:
  id: int


@strawberry_django.type(Project, name='Project')
class ProjectType:
  id: int
  name: str
  latest_issue: IssueType | None = strawberry_django.field(field_name='issues')


@strawberry.type
class Query:
  projects: ListConnectionWithTotalCount[ProjectType] = strawberry_django.connection()

```

This example seems a bit contrived, however it should show the bug. When querying as follows:
```graphql
query {
  projects {
    name latestIssue { id }
}
```
There will be a query for projects (👍), a prefetch-query for issues (👍) and then another query _for each project_ fetching the first issue (🙁). 

A fix could look like this, implemented as a custom `StrawberryDjangoField` subclass here:
```python
class StrawberryDjangoFieldWithFixedPrefetchInSomeCases(StrawberryDjangoField):
    def get_queryset_hook(self, info: Info, **kwargs):
        if self.is_connection or self.is_paginated or self.is_list:
            return super().get_queryset_hook(info, **kwargs)
        elif self.is_optional:
            def qs_hook(qs: QuerySet):  # type: ignore
                qs = self.get_queryset(qs, info, **kwargs)
                if is_optimized_by_prefetching(qs):
                    return next(iter(qs), None)
                else:
                    return qs.first()
            return qs_hook
        else:
            def qs_hook(qs: QuerySet):  # type: ignore
                qs = self.get_queryset(qs, info, **kwargs)
                if is_optimized_by_prefetching(qs):
                    try:
                        return next(iter(qs))
                    except StopIteration:
                        raise qs.model.DoesNotExist(
                            "%s matching query does not exist." % qs.model._meta.object_name
                        )
                else:
                    return qs.get()
            return qs_hook
```

I will submit a proper pull request if there are no objections.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/662">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/662/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/662/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @diesieben07 ,

I'm just seeing this right now.

> I will submit a proper pull request if there are no objections.

PRs are always welcomed! Go ahead :)
