### ISSUE TITLE
Weird strawberry_django.field resolver slowdown.

### ISSUE THREAD

**Issue by NT-Timm** [strawberry-graphql/strawberry-django#672]
It seems there's a big slowdown somewhere in the strawberry_django field/model_property resolver code.
It's really hard to debug it though.
It's a general slowdown between 2.5-3 times in speed.

## Describe the Bug

On the strawberry type level. (HelloType is made with strawberry_django.type()) 
```
    # this has no slowdown
    @strawberry.field()
    def hello(self) -> str:
        return "test"

    #this has slowdown
    hello: str = strawberry_django.field(annotate=Value("test"))
    hello: str = strawberry_django.field(annotate={"hello": Value("test")})
    @strawberry_django.field()
    def hello(self) -> str:
        return "test"
```

On the django model level. (HelloModel(models.Model))
With `hello: strawberry.auto` in HelloType
```
    # this has slowdown
    @model_property()
    def hello(self) -> str:
        return "test"

    # this has no slowdown.
    @model_property(annotate={"hello": Value("test")})
    def hello(self) -> str:
        # this code is not triggered
        return "test"
```

## System Information

django = "~5.1"
strawberry-graphql = "~0.253"
strawberry-graphql-django = "~0.51"

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/672">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/672/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/672/pledge.svg">
</picture>
</a>

**Comment by NT-Timm** [comment]
I just found out that this only happens with the AsyncGraphQLView and not the GraphQLView.

**Comment by diesieben07** [comment]
> I just found out that this only happens with the AsyncGraphQLView and not the GraphQLView.

This suggests to me that this happens because every model_property will be resolved inside `sync_to_async` when using `AsyncGraphQLView`. This happens, because a model property might access the database.
So every model_property access requires a context switch to the main thread, which adds overhead. If you add a prefetching annotation, this is handled by the optimizer _in one go_ so you don't have _many context switches_, but just _one_ for loading the optimized QuerySet.

If you make your model_property function async, it should remove the slowdown, because it won't need to be passed through `sync_to_async`.

**Comment by NT-Timm** [comment]
Making my model_property function async doesn't work unless I manually await it in the strawberry_django.field.
I tried it with strawberry.auto and it got a coroutine back instead of the expected result. (Seems like the resolving code doesn't check model_property for asyncness?
