### ISSUE TITLE
Ordering does not handle sorting by multiple fields when order is a variable

### ISSUE THREAD

**Issue by diesieben07** [strawberry-graphql/strawberry-django#677]
When sorting by multiple fields using `@strawberry_django.order`, the order in which the sorting is applied (i.e. "Sort by name then age" vs "Sort by age then name") is determined by the order of the fields with in the order object (this is a different issue). This does not work if the order argument is given as a variable.

## Describe the Bug

Following schema is used:
```py
@strawberry_django.order(User)
class UserOrder:
  name: auto
  birthday: auto

@strawberry_django.type(User, order=UserOrder)
class UserType:
  id: auto
  name: auto
  birthday: auto

@strawberry.type
class Query:
  users: list[UserType] = strawberry_django.field()
```

This query will correctly sort by birthday, then name:
```gql
query sortedUsers {
  users(order: { birthday: ASC, name: ASC }) {
    id name birthday
  }
}
```
This will sort by name, the birthday, it will take the order as defined in the `UserOrder` class, not as given by the client:
```gql
query sortedUsers($order: UserOrder) {
  users(order: $order) {
    id name birthday
  }
}
```
Variables:
```json
{
  "order": {
    "birthday": "ASC",
    "name": "ASC"
  }
}
```

## System Information

 - Operating system:
 - Strawberry version (if applicable):

## Additional Context

The reason for this is this check:
https://github.com/strawberry-graphql/strawberry-django/blob/62dc99429ad1142b7a7a3f84da8115307dbadee2/strawberry_django/ordering.py#L174-L176

In the 2nd example above, `arg.value` will be a `VariableNode`. The fix will be to handle that case as well and in that case look info `info.variable_values` instead of simply bailing out.

I will try to work on a PR to fix this bug soon.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/677">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/677/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/677/pledge.svg">
</picture>
</a>

**Comment by diesieben07** [comment]
Looking into this, it seems impossible to fix for inputs provided as variables, because of this piece of code in graphql-core:
https://github.com/graphql-python/graphql-core/blob/59d478af061af9721a9a04ebc6def17c6fc30c55/src/graphql/utilities/coerce_input_value.py#L98-L119

This "coerces" every object in the variables by mapping it to the matching input type. The way it does this is that it loops through the fields _of the input type_, building up a new dict. The resulting dict will then _always_ have the fields in the order that they were defined in the schema and the order given by the user is lost.
I am not sure there is a way around that without making even more horrible hacks.

To me that just means that #678 is even more imporant.

**Comment by bellini666** [comment]
Going to close this as duplicated of https://github.com/strawberry-graphql/strawberry-django/issues/615 :)
