### ISSUE TITLE
Pagination not working when resolver specified on field

### ISSUE THREAD

**Issue by FernandoNarvaez1904** [strawberry-graphql/strawberry-django#89]
I do not know if this is a Bug or a Feature, but the pagination feature seems not to work whenever a resolver is specified in any way. Let me explain. 

Pagination **will work fine** with the following code:

```python
from typing import List

import strawberry
import strawberry_django

from user.api.types import FriendRequestType


@strawberry.type
class Query:
    pending_friend_request: List[FriendRequestType] = strawberry_django.field(pagination=True)
```
Schema Result:
![image](https://user-images.githubusercontent.com/47584735/153454371-a5c6a305-47ad-4992-99c0-37535c8f6285.png)

But, When I specified a resolver or just write the function directly into query, pagination stops working:

```python
@strawberry.type
class Query:
    pending_friend_request: List[FriendRequestType] = strawberry_django.field(
        resolver=pending_friend_request_query_resolver, pagination=True)
```
```python
 @strawberry_django.field(pagination=True)
 @login_required_decorator
 async def pending_friend_request(self, info: Info) -> List[FriendRequestType]:
        # My code...    
```
![image](https://user-images.githubusercontent.com/47584735/153455938-3084ddc0-646b-470f-a7e9-f67aa699a9e8.png)

Can you please explain to me, if this is a bug or a feature? Is there any workaround available? Thanks in advance

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/89">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/89/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/89/pledge.svg">
</picture>
</a>

**Comment by la4de** [comment]
You are right, pagination works only with default resolver. You can reuse existing logic from `strawberry.django.pagination`. There are `OffsetPaginationInput` input type and `apply` function which do the job.

The bast we could do now is to document that pagination works only with default resolver and return an error if someone tries to use it with resolver field argument.

**Comment by la4de** [comment]
Example pushed to repo
https://github.com/strawberry-graphql/strawberry-graphql-django/blob/main/tests/test_pagination.py#L52-L67

**Comment by bellini666** [comment]
This has been supported for some time now so I'm going to mark this as resolved :)

If that's not the case, please comment here so that we can reopen and reevaluate what needs to be done
